# Generated by Django 2.0.10 on 2019-01-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nzoz', '0003_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourFrom', models.TimeField()),
                ('hourTo', models.TimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nzoz.Clinic')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nzoz.Day')),
            ],
        ),
    ]
